AF_XDP-interaction: Fix to work on newer kernels supporting bpf_link
Program fails on newer kernels, with error message:

 libbpf: Netlink-based XDP prog detected, please unload it in order to launch AF_XDP prog
 ERROR: Can't setup AF_XDP socket "Invalid argument"

Since kernel v5.13 libbpf version, when bpf_link support is
detected then libbpf/xsk require XDP/BPF programs use this feature.
See kernel commit 10397994d30f ("libbpf: xsk: Use bpf_link").

To continue using our netlink-based XDP attach approach,
instruct libbpf/xsk to not be in change of loading the
BPF-prog.  As our XDP-prog is special it also makes
to control this ourselves.

This is achived with the flag XSK_LIBBPF_FLAGS__INHIBIT_PROG_LOAD

 xsk_cfg.libbpf_flags = XSK_LIBBPF_FLAGS__INHIBIT_PROG_LOAD

Remember to update the xskmap manually.

Fixes: 10397994d30f ("libbpf: xsk: Use bpf_link")
Signed-off-by: Jesper Dangaard Brouer <brouer@redhat.com>