configure: Add libcap check
The xdpsock needs libcap, otherwise it will compile failed. So we can
add the libcap check in configure.

xdpsock.c:27:10: fatal error: sys/capability.h: No such file or directory
   27 | #include <sys/capability.h>
      |          ^~~~~~~~~~~~~~~~~~

The test result:

dylane@2404:~/sdb/bpf-examples$ ./configure
clang: 18.1.3 (1ubuntu1)
libcap support: yes
libmnl support: yes
libbpf support: submodule
ELF support: yes
zlib support: yes
libxdp support: submodule

Signed-off-by: Tao Chen <chen.dylane@linux.dev>